apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: security-editor
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "delete", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: namespace-editor
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: namespace-observer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-editor
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "persistentvolumes"]
    verbs: ["create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-observer
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
